language: node_js
node_js:
- '0.11'
- '0.10'

notifications:
  email: false

language: node_js

node_js:
- '7'

cache:
  directories:
    - node_modules

branches:
   only:
      - master

install:
   - npm i --silent -g @angular/cli
   - npm i --silent -g angular-cli-ghpages

script:
   - npm i --silent
   - ng build --prod --progress=false --base-href https://colmena.io/$GH_REPO/
   - echo 'colmena.io' > dist/CNAME
   - cp dist/index.html dist/404.html
   - ngh angular-cli-ghpages --repo=https://GH_TOKEN@github.com/$GH_USER/$GH_REPO.git --name="Travis CI" --email=travis@example.com
